title: "Black Blog"
author: "Jan Černý"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
date_format: "%B %d, %Y"

# Layout
sidebar: true               # show a sidebar instead of the usual header
show_excerpts: false          # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_logo: true              # always keep the site title visible
show_title: false

# Styling
minimal: false               # use simpler style
sidebar_limit: "55em"        # css limit of showing side bar

# Menu
navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: info-circle}

# Menu external
external:                   # see http://fontawesome.com/icons
  - {title: Projects, icon: project-diagram, url: "/projects"}
  - {title: References, icon: address-card, url: "/ref"}
  - {title: Meziklasí, icon: seedling, url: "http://www.meziklasi.cz/"}
  - {title: Lyricall, icon: pen-fancy, url: "https://www.lyricall.cz/"}
  - {title: Repository, icon: github, url: "https://github.com/yagarea/blackblog"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

# References items
references:
  - {title: Github, icon: "github-icon.png", url: "https://github.com/yagarea/"}
  - {title: StackOverflow, icon: "stackoverflow-icon.png", url: "https://stackoverflow.com/users/7274239/"}
  - {title: Bandcamp, icon: "bandcamp-icon.png", url: "https://bandcamp.com/yagarea"}
  - {title: Email, icon: "email-icon.png", url: "mailto:j.cerny.zdar@gmail.com"}
  - {title: Instagram, icon: "instagram-icon.png", url: "", note: "Soon"}
  - {title: Facebook, icon: "facebook-icon.png", url: "", note: "Soon"}

kramdown:
    math_engine: katex

comments:
    commentsapp-id: "Kh5zcvkB"
    enabled: true
    limit: 5

plugins:
 - jekyll-feed
 - jekyll-gzip

#Render options
disable_disk_cache: false
exclude: ["*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "scripts/", "LICENSE.txt", "Rakefile", "_meta", "katex.min.js"]
include: [".htaccess"]
timezone: "Europe/Prague"
JEKYLL_ENV: development

#Compression settings
gzip:
  replace_files: true
  extensions: [".html", ".css", ".js", ".txt", ".ttf", ".atom", ".stl", ".xml", ".svg", ".eot"]

