title: "Black Blog"
author: "Jan Černý"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
date_format: "%B %d %Y"

# Layout
sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_logo: true              # always keep the site title visible
show_title: false

# Styling
sidebar_limit: "55em"        # css limit of showing side bar

# Menu
navigation:
  - {file: "index.html", icon: home}
  - {file: "about.md", icon: info-circle}
  - {file: "projects.md", icon: project-diagram }
  - {file: "music.md", icon: music }
  - {file: "references.md", icon: address-card}

# Menu external
external:                    # see http://fontawesome.com/icons
  - {title: Meziklasí, icon: seedling, url: "https://meziklasi.cz/"}
  - {title: Lyricall, icon: pen-fancy, url: "https://lyricall.cz/"}
  - {title: Repository, icon: github, url: "https://github.com/yagarea/blackblog"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

# References items
references:
  - {title: Email, nickname: "cerny@matfyz.cz", icon: "email-icon.png", url: "mailto:cerny@matfyz.cz"}
  - {title: Telegram, nickname: "yagareas", icon: "telegram-icon.png", url: " https://t.me/yagareas"}
  - {title: Matrix, nickname: "@jc:matrix.ucw.cz", icon: "matrix-icon.png", url: "https://matrix.to/#/@jc:matrix.ucw.cz" }
  - {title: Github, nickname: "yagarea", icon: "github-icon.png", url: "https://github.com/yagarea/"}
  - {title: StackOverflow, nickname: "Jan Černý", icon: "stackoverflow-icon.png", url: "https://stackoverflow.com/users/7274239/"}
  - {title: Bandcamp, nickname: "yagarea", icon: "bandcamp-icon.png", url: "https://bandcamp.com/yagarea"}


collections:
  music:
    output: true
    permalink: /music/:title/

plugins:
  - jekyll-feed
  - jekyll-gzip
  - jekyll-tidy
  - jektex

# Render options
disable_disk_cache: false
exclude: ["*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "scripts/", "LICENSE.txt", "Rakefile", "_meta", "katex.min.js", "makefile"]
include: [".htaccess"]
timezone: "Europe/Prague"
JEKYLL_ENV: development

# Latex rendering settings
jektex:
  cache_dir: ".jekyll-cache"
  ignore: ["*.xml", "*.css", "*.sass", "*.svg", "*.js", "*.map"]
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
    - ["\\P", "\\mathbb{P}"]

# Compression settings
gzip:
  replace_files: true
  extensions: [".html", ".css", ".js", ".txt", ".ttf", ".atom", ".stl", ".xml", ".svg", ".eot"]

# Clean rendered html
jekyll_tidy:
  exclude: ["_includes/*"]
  ignore_env: "testing"
  compress_html: false


